### ISSUE TITLE
New Pro test

### ISSUE THREAD

**Issue by noamhoze** [noamhoze/walabot#48]
Please build the following version for the index page: 

On mobile it will look packed if you use the current design, 
so please follow the solution offered [here](http://www.foolproof.co.uk/thinking/making-product-comparison-work-on-mobile/).

![original-walabot-comparison-table](https://cloud.githubusercontent.com/assets/20975533/25009534/a2cd0922-206f-11e7-87ac-d33553c969d1.jpg)

**Comment by noamhoze** [comment]
@amitzur, please add the following row to the table:
"Working on Linux, Windows and RPI".

**Comment by amitzur** [comment]
With all checked?

**Comment by noamhoze** [comment]
Yes

**Comment by noamhoze** [comment]
This is related to #52.
