### ISSUE TITLE
Create a refund policy link

### ISSUE THREAD

**Issue by noamhoze** [noamhoze/walabot#60]
Please create in the **footer** a link "refund policy" and link it here https://walabot.com/walabot-tc-416.pdf

![image](https://cloud.githubusercontent.com/assets/20975533/26195767/910a2af0-3bc5-11e7-87c9-75233440a8b1.png)

**Comment by viebel** [comment]
@noamhoze  According to [Google Translate](https://translate.google.com/#en/de/refund%20policy) in german, the "refund policy" string is going to be "Rückgaberecht"
Is that correct?

**Comment by noamhoze** [comment]
Yes

**Comment by viebel** [comment]
Done
